{{- if .Values.vault.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-{{ include "<CHARTNAME>.fullname" . }}
spec:
  refreshInterval: {{ .Values.vault.interval | quote }}
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: SecretStore
  target:
    name: {{ .Values.vault.target }}
  dataFrom:
    - extract:
        key: {{ .Values.vault.extract }}
{{- end }}
