apiVersion: v1
kind: Service
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels: {{- include "<CHARTNAME>.labels" . | nindent 4 }}
  {{- if .Values.serviceAnnotations.enabled }}
  annotations:
    {{- include "<CHARTNAME>.cloud.loadBalancerProvider" . | nindent 4 }}
    {{- with .Values.serviceAnnotations.custom }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.changePort }}
      targetPort: {{ .Values.service.servicePort }}
      protocol: TCP
      name: http
  selector: {{- include "<CHARTNAME>.selectorLabels" . | nindent 4 }}
